spring.application.name=afterFail
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/afterFail?useSSL=false&
spring.datasource.username=root
spring.datasource.password=K4283.mN,e90
spring.security.user.name=admin
spring.security.user.password=1234
spring.security.enabled=false

